
services:
  tinyheterofam:
    build:
      context: .
      dockerfile: Dockerfile
    image: heterofam:latest
    ports:
      - 8080:8080
    volumes:
      - ../MyHeteroFAM/archive:/HeteroFAM/archive
      - ../MyHeteroFAM/Work:/HeteroFAM/Work
      - ../MyHeteroFAM/Projects:/HeteroFAM/Projects
      - /home/bylaska/Public/HeteroFAM/Public/uploads:/HeteroFAM/Public/uploads
      - /home/bylaska/Public/HeteroFAM/Public/chemdb_hold:/HeteroFAM/Public/chemdb_hold
      - /home/bylaska/Public/HeteroFAM/Public/eric_data:/HeteroFAM/Public/eric_data
    environment:
      - NWCHEM_EXTRA_GROPUS=/HeteroFAM/static/nwchem/extragroups.dat
    depends_on:
      - mariadb
      - mongodb

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 05291999
      MYSQL_DATABASE: TNT_Project
      MYSQL_USER: hetero
      MYSQL_PASSWORD: solid
    command: --bind-address=0.0.0.0
    restart: always
    volumes:
      - ../MyHeteroFAM/mariadb:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ../MyHeteroFAM/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: hetero
      MONGO_INITDB_ROOT_PASSWORD: solid
      MONGO_INITDB_DATABASE: HeteroFAM # Set the default database name for MongoDB
    command: mongod --auth --bind_ip_all # Enable authentication and bind to all interfaces
